### ISSUE TITLE
Error : "cannot update screenshot, no connection" When i try to Refresh Screenshot  in fmbt-scripter for tizen

### ISSUE THREAD

**Issue by mafrul** [01org/fMBT#46] opened 2015-09-10 07:14 UTC
Testing Procedure:
1. Go terminal run "fmbt-scripter"
2. Then select "Rec" and "Control"
3. Go the "Bitmap" Menu then select "Auto-select when recording"
4. Then Select "File" ->>" New Tizen" and try to refresh Screenshot  Press (eval) refresh button

Observe that in console :
cannot update screenshot, no connection
>>>

**Comment by askervin** [comment] 2015-09-17 08:30
Hi @mafrul, thanks for reporting the problem. Unfortunately I cannot reproduce the issue with my RD-PQ device.

Would you tell what the following command prints to your terminal:

python -c 'import fmbttizen; fmbttizen.Device().refreshScreenshot().save("screenshot.png")'

**Comment by mafrul** [comment] 2015-09-30 10:52
Before working on fmbt make sure your devices is root on mode. This is the solution. Thank you for your response.

**Comment by askervin** [comment] 2015-09-30 11:35
Thanks for sharing this! Closing.

**Closed by askervin** 2015-09-30 11:35 UTC
